openattic_repo: ~/openattic
deepsea_repo: ~/DeepSea

#libvirt_host: @ip_address@
#libvirt_user: @user_name@
#libvirt_use_ssl: true

vm_memory: 4096
vm_cpus: 2
vm_storage_pool: default
vm_num_volumes: 2
#vm_volume_size: 8192 # VirtualBox
vm_volume_size: 8G

nfs_auto_export: true
build_openattic_docker_image: true
